### ISSUE TITLE
关于异步分发的问题

### ISSUE THREAD

**Issue by goxofy** [0xDkd/auxpi#53]
是不是只有在后台分发管理界面上传的图片才会进行异步分发，前台直接选择图床然后上传图片是不会进行自动分发的？

**Comment by aimerforreimu** [comment]
是的，当前版本暂不支持让用户使用分发

**Comment by goxofy** [comment]
明白了谢谢

**Comment by goxofy** [comment]
能否只监听本地127.0.0.1:2333，这样外面套一层nginx反代就行了

**Comment by aimerforreimu** [comment]
一直都是可以的啊，正常来说使用 nginx 就是这么做的

**Comment by goxofy** [comment]
现在是如果外面反代了一层nginx的话，在外部用ip+端口还是可以访问的，只监听127.0.0.1的之后就只能通过nginx里的servername访问了

**Comment by aimerforreimu** [comment]
可以增添此选项，感谢建议
